Cod 19
crazymaza/CodeBusters pull request #12
Opened 2023-06-27 07:44 UTC by Avenntador

### Какую задачу решаем
Реализовать логику авторизации

### Что сделано
- Подключен redux toolkit
- Подключен api авторизации практикума 
- Реализована логика авторизации
- Пользователь не может зайти ни на какую страницу пока не авторизован

2023-06-28 06:02 UTC, OlgaNoz commented on packages/client/src/api/Auth/index.ts
> +export interface UserInfo {
мб вынести интерфейсы в отдельный файл?

2023-06-28 06:02 UTC, OlgaNoz commented
Привет, поправь конфликты, пжл и можно будет заапрувиь

2023-06-28 07:24 UTC, alexYurin commented on packages/client/src/api/Auth/index.ts
> +import BaseApi from '../Base'
Если нужно импортировать что-то из директории, которая лежит не в корне с файлом, куда импортируешь, то лучше использовать алиасы. Так и выглядит лучше и в случае, если нужно будет переместить файл в другое место, то импорт не сломается
Здесь, например, можно так
`import { BaseApi } from '@/api'`

2023-06-28 07:24 UTC, alexYurin commented on packages/client/src/api/Auth/index.ts
> +export interface UserInfo {
Поддерживаю Олю

2023-06-28 07:42 UTC, alexYurin commented on packages/client/src/store/index.ts
> +import authSlice from '@/store/slices/authSlice'
Давай создадим index.ts в store/slices/ и там будем экспортировать все слайсы
типа 
`export { defautl as authSlice } from './authSlice'`
и в компоненте
`import { authSlice } from '@/store/slices'`

2023-06-28 07:43 UTC, alexYurin commented on packages/client/src/store/slices/authSlice/index.ts
> +}
Может добавим export на всякий)?

2023-06-28 07:44 UTC, alexYurin reviewed
Есть небольшие замечания

2023-06-28 07:54 UTC, crazymaza commented on packages/client/src/pages/SignIn/index.tsx
> +      .catch(error => console.log(error))
API Яндекса выдавало ошибку, если пользователь уже был ранее авторизован и сохранился токен. 
Предлагаю такой вариант ошибки обработать и перенаправлять пользователя на главную страницу.

```js
.catch((err) => {
    if (err.message === "User already in system") {
       navigate('/')
    }
})
```

2023-06-28 14:43 UTC, OlgaNoz reviewed
все хорошо)

2023-06-28 14:44 UTC, OlgaNoz approved these changes

2023-06-29 07:06 UTC, IvanPeleshok commented on packages/client/src/pages/SignIn/index.tsx
> +    dispatch(signin({ login, password }))
Во-первых, предлагаю переписать колбеки на async / await
Во-вторых, не вижу причин, чтобы внутри одной санки вызывать другую (пример, https://stackoverflow.com/questions/66613260/how-to-dispatch-asyncthunk-inside-another-asyncthunk)

Таким образом, код станет более чище и проще

2023-06-29 07:07 UTC, IvanPeleshok commented on packages/client/src/pages/SignIn/index.tsx
> +        if (isAxiosError(error)) {
Предлагаю написать всё в одном условии
```
if (
  условие1
  && условие2
) { body }
```

2023-06-29 07:09 UTC, IvanPeleshok commented on packages/client/src/router/useAuth.ts
> +      dispatch(getUserInfo())
Переписать на async / await

2023-06-29 07:09 UTC, IvanPeleshok requested changes
Есть небольшие замечания

2023-06-29 10:11 UTC, IvanPeleshok approved these changes

2023-06-29 10:26 UTC, merged