Cod 21
crazymaza/CodeBusters pull request #18
Opened 2023-06-30 20:45 UTC by yandexlispeth

### Какую задачу решаем
Вёрстка страницы форума и страницы топика с возможностью оставлять комментарий

### Скриншоты/видяшка (если есть)

<img width="1630" alt="forum_main" src="https://github.com/crazymaza/CodeBusters/assets/124637674/5416e45f-7feb-47a1-ba14-656078b9aae9">
<img width="1542" alt="forum_topic" src="https://github.com/crazymaza/CodeBusters/assets/124637674/0d37f76e-b5f7-42a3-a453-bcdb7184fb01">

### TBD (если есть)

2023-07-01 10:04 UTC, crazymaza commented on packages/client/src/pages/Forum/index.tsx
> +  const handleCloseDialog = () => {
Добавить event.preventDefault() .

2023-07-01 10:05 UTC, crazymaza commented on packages/client/src/pages/Forum/index.tsx
> +          <Button
Я бы ещё добавил возможность закрытия диалогового окна без создания темы. 
Ещё одну кнопку рядом или крестик.

2023-07-01 10:11 UTC, crazymaza commented on packages/client/src/pages/Forum/styles.module.scss
> +            border-radius: 1.5rem;
width: 99%; 
Иначе появляется горизонтальная прокрутка

2023-07-01 10:15 UTC, crazymaza commented on packages/client/src/pages/ForumTopic/index.tsx
> +    date: new Date().toDateString(),
давай форматирование даты перенесём в код, так как мы её будем получать с сервера:
<ListItemText className={cx('comments-item-date')}>
              {date.toLocalDateString()}
            </ListItemText>

2023-07-01 10:17 UTC, crazymaza commented on packages/client/src/pages/ForumTopic/index.tsx
> +          <ListItem className={cx('comments_item')}>
Проверь наименования классов. Не везде по БЭМ.

2023-07-01 10:18 UTC, crazymaza commented on packages/client/src/pages/ForumTopic/styles.module.scss
> +  background: url(../../assets/images/background_light_theme.png) no-repeat;
переделай на images/background_light_theme.png

2023-07-01 10:23 UTC, crazymaza commented on packages/client/src/pages/ForumTopic/index.tsx
> +  <div className={cx('page-content-close')}>
Можно сделать обработку нажатия, чтобы был возврат на страницу форума.

2023-07-01 10:23 UTC, crazymaza commented on packages/client/src/pages/ForumTopic/index.tsx
> +          <form className={cx('topicpage__form')}>
onSubmit с event.preventDefault();

2023-07-01 10:25 UTC, crazymaza commented on packages/client/src/pages/Forum/index.tsx
> +            onClick={handleCloseDialog}>
Так как это форма, то лучше повесить обработчик onSubmit() на форму, отсюда убрать. 
Таким образом я смогу создать новую тему как нажатием на кнопку, так и по нажатию клавиши Enter.

2023-07-01 10:27 UTC, crazymaza commented on packages/client/src/pages/Forum/index.tsx
> +  // const navigate = useNavigate()
Пасхалка?

2023-07-01 10:27 UTC, crazymaza reviewed
Есть замечания

2023-07-02 23:53 UTC, yandexlispeth commented on packages/client/src/pages/ForumTopic/index.tsx
> +  <div className={cx('page-content-close')}>
Добавила ссылку "К списку форумов" и крестик для возврата в главное меню

2023-07-03 11:24 UTC, crazymaza approved these changes
Не забудь передать в личный зачёт

2023-07-04 09:59 UTC, IvanPeleshok commented on packages/client/src/pages/Forum/index.tsx
> +const topicsList: {
Давай вынесем в отдельный модуль (файл)
+Читаемость
+Декомпозиция (переиспользуемость, масштабируемость)

2023-07-04 10:00 UTC, IvanPeleshok commented on packages/client/src/pages/Forum/index.tsx
> +const topicsPopular = [
Аналогично

2023-07-04 10:01 UTC, IvanPeleshok commented on packages/client/src/pages/Forum/index.tsx
> +  const [open, setOpen] = React.useState(false)
Для удобства, предлагаю импортировать React следующим образом:
import { useState } from 'react'
Тогда не будет необходимость доставать его из объекта React
Меньше строк кода

2023-07-04 10:02 UTC, IvanPeleshok commented on packages/client/src/pages/Forum/index.tsx
> +  const renderCloseButton = () => {
Декомпозируем код, выносим элементы из общего компонента
Импортируем его в общую сущность, собирая конструктор

+Чистота кода
+Масштабируемость (переиспользуемость)

2023-07-04 10:03 UTC, IvanPeleshok commented on packages/client/src/pages/Forum/index.tsx
> +  const renderDialog = () => (
Аналогично

2023-07-04 10:04 UTC, IvanPeleshok commented on packages/client/src/pages/ForumTopic/index.tsx
> +import { Button } from '@/components'
Аналогичные замечания и в этом файле

2023-07-04 10:05 UTC, IvanPeleshok requested changes
Есть замечания:

Декомпозируем код, разбиваем его на мелкие сущности (нет необходимости писать файлы по 500 строк кода, когда можно разнести всё по файликам, а потом, как в конструкторе, собрать что-то большее)

2023-07-04 18:03 UTC, yandexlispeth commented on packages/client/src/pages/Forum/index.tsx
> +  const renderCloseButton = () => {
В 6-м спринте у меня задача на рефакторинг, по коду уже много разбросано подобных  "компонентов", пометила себе туду, чтобы не забыть при рефакторинге.

2023-07-04 18:04 UTC, yandexlispeth commented on packages/client/src/pages/Forum/index.tsx
> +  const renderDialog = () => (
Всё поправлю в рамках задачи на рефакторинг в 6м спринте

2023-07-04 20:08 UTC, IvanPeleshok approved these changes

2023-07-04 20:09 UTC, merged