Cod 31
crazymaza/CodeBusters pull request #22
Opened 2023-07-05 12:56 UTC by alexYurin

### Какую задачу решаем
Создать механику игры на Canvas API

- Добавлена анимация движения трассы (бегущие с верху вниз границы трека)
- Скорость анимации периодически увеличивается, для имитации увеличения скорости движения машины
- Добавлена машина и ее управление (курсоры влево и вправо)
- Добавлена обработка вылета с трассы (столкновение с левой или правой границей трека)
- Процесс игры можно запустить или остановить с помощью методов `run()` и `stop()` у движка

### Скриншоты/видяшка (если есть)
<img width="1511" alt="Снимок экрана 2023-07-05 в 19 42 02" src="https://github.com/crazymaza/CodeBusters/assets/24264027/e494818a-c09f-4169-8146-9d8f2dc8a492">

### TBD (если есть)

2023-07-05 19:15 UTC, OlgaNoz reviewed
хорошо бы, чтобы кто-нибудь еще из ребят посмотрел, мб заметят больше, чем я

2023-07-05 19:15 UTC, OlgaNoz commented on packages/client/src/engine/Core/index.ts
> +    this.process = 'play'
мб 'play' ,'stop', 'pause' вынести в какой-нибудь enum?

2023-07-05 19:15 UTC, OlgaNoz commented on packages/client/src/pages/Play/hooks/useEngine.ts
> +    if (
точно так перенос должен выглядеть, а не
if (carRef.current instanceof HTMLCanvasElement &&
? (просто не очень читаемо)

2023-07-06 08:31 UTC, alexYurin commented on packages/client/src/engine/Core/index.ts
> +    this.process = 'play'
Хорошая идея, вынес в enum

2023-07-06 08:32 UTC, alexYurin commented on packages/client/src/pages/Play/hooks/useEngine.ts
> +    if (
Если ты про сам перенос, то так prettier сам перенес. А так вынес условие в отдельную переменную `isDefineLayers`

2023-07-06 08:45 UTC, Avenntador approved these changes
Молодец, огромную работу проделал) Критических замечаний не нашел, но прежде чем мерджить, пусть и кто-нибудь еще апрувнет)

2023-07-06 09:54 UTC, OlgaNoz approved these changes
Супер! Молодец) согласна с Булатом, работа огромная)

2023-07-06 16:08 UTC, OlgaNoz commented
@alexYurin а ссылку на pr добавил на платформе? А то что-то и статус не меняется на Review practicum, и времени прошло немало с момента апрува

2023-07-06 16:15 UTC, alexYurin commented
> @alexYurin а ссылку на pr добавил на платформе? А то что-то и статус не меняется на Review practicum, и времени прошло немало с момента апрува

Да, добавил. не знаю почему так

2023-07-06 21:10 UTC, yandexlispeth commented
Круто!

2023-07-06 21:12 UTC, yandexlispeth approved these changes

2023-07-07 12:26 UTC, IvanPeleshok commented on packages/client/src/engine/Core/index.ts
> +export default class CBEngine {
Рекомендация: не пытаться сокращать названия сущностей, т.к код мы пишем для других людей

2023-07-07 12:30 UTC, IvanPeleshok commented on packages/client/src/engine/Core/index.ts
> +    return this
Необязательно внутри конструктора возвращать this

2023-07-07 12:33 UTC, IvanPeleshok commented on packages/client/src/engine/Objects/Car.ts
> +      case 'ArrowLeft':
Предлагаю вынести в Enum
Плюсы: переиспользуемость, упрощает рефакторинг

2023-07-07 12:35 UTC, IvanPeleshok commented on packages/client/src/engine/Objects/Track.ts
> +        side === 'left'
Строковые left / right тоже имеет смысл вынести в Enum

2023-07-07 12:36 UTC, IvanPeleshok requested changes
Всё здорово, но есть небольшие замечания

2023-07-07 22:19 UTC, IvanPeleshok commented
Предлагаю перевести работу на ревью, заапрувлю работу :)

2023-07-08 04:21 UTC, alexYurin commented on packages/client/src/engine/Objects/Car.ts
> +      case 'ArrowLeft':
Поместил все объекты в отдельные папки и вынес типы. Добавил enum

2023-07-08 04:21 UTC, alexYurin commented on packages/client/src/engine/Objects/Track.ts
> +        side === 'left'
Также вынес

2023-07-08 04:35 UTC, alexYurin commented
> Предлагаю перевести работу на ревью, заапрувлю :)

Перевел)

2023-07-08 09:25 UTC, IvanPeleshok approved these changes

2023-07-08 09:54 UTC, merged