COD 34. Предварительная реализация
crazymaza/CodeBusters pull request #28
Opened 2023-07-10 09:15 UTC by crazymaza

### Какую задачу решаем
Добавление препятствий на трассу

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-07-11 11:22 UTC, crazymaza commented
Не знаю почему столько файлов залетело в коммит. 
Изменения делал в файлах engine/Core, engine/Objects/Barrier и pages/Play

2023-07-11 16:33 UTC, OlgaNoz reviewed
Посмотрела, все ок, но возникло предложение, мб некоторые числа, которые для вычислений используются в какие-нибудь константы вынести? А то их и так много, что начинаешь путаться, ну и несколько раз увидела цвет '#e3bc27', мб и цвета тоже отдельно добавить?

+ еще конфликты надо пофиксить

2023-07-13 12:08 UTC, OlgaNoz approved these changes
здорово)

2023-07-13 19:02 UTC, alexYurin approved these changes
Круто! Теперь стало еще интереснее играть)

2023-07-13 19:38 UTC, Olegas requested changes
Есть минорное замечания - опечатка в названии стандартного свойства (width->with)
Есть странные решения в коде. Написал к ним вопросы. Надо или объяснить зачем так или переделать.

2023-07-13 19:38 UTC, Olegas commented on packages/client/src/engine/Core/index.ts
>              CarObject.dimensions.with
Опечатка в слове width

2023-07-13 19:38 UTC, Olegas commented on packages/client/src/engine/Core/index.ts
> +          BarrierObject.currentSpec.trackHeight -
Очень странно с архитектурной точки зрения, что положение машины высчитывается через какое-то свойство объекта препятствия (пусть это даже и длина видимой трассы, которая константа).

2023-07-13 19:38 UTC, Olegas commented on packages/client/src/pages/Play/hooks/useEngine.ts
> +        barrierObject.draw(0, baseBarrierSpec)
Еще один странный участок, с точки зрения архитектуры.
1. Создаем объект barrier
2. C с помощью статического метода класса создаем (а по факту возвращаем статическое свойство класса) и немного правим на основании аргумента набор характеристик
3. Передаем эти характеристики этому же экземпляру в метод draw.

Зачем так сложно? Почему нельзя baseBarrierSpec инкапсулировать внутри класса и использовать изнутри draw не раскрывая эту деталь реализации наружу?

2023-07-14 08:54 UTC, crazymaza commented on packages/client/src/pages/Play/hooks/useEngine.ts
> +        barrierObject.draw(0, baseBarrierSpec)
Сделал второй параметр опциональным

2023-07-14 08:56 UTC, crazymaza commented on packages/client/src/engine/Core/index.ts
> +          BarrierObject.currentSpec.trackHeight -
Переделал.  Теперь в хуке useEngine прокидываю в baseCarSpecs ещё и высоту трека, а в самом классе машины высчитываю её положение по оси Y

2023-07-14 19:27 UTC, Olegas approved these changes

2023-07-15 06:09 UTC, merged