Cod 36
crazymaza/CodeBusters pull request #36
Opened 2023-07-14 11:51 UTC by yandexlispeth

### Какую задачу решаем

- добавлен канвас слой с задним фоном, фон зациклен, движется вместе с игрой,
- добавлены полосы на трассу,
- добавлены спрайты для препятствий и машинки

### Скриншоты/видяшка (если есть)

![demo](https://github.com/crazymaza/CodeBusters/assets/124637674/44a3c925-04bb-45b5-b798-c7c4c58398c9)

### TBD (если есть)

2023-07-14 12:18 UTC, yandexlispeth commented
Ветку брала от ветки Игоря COD-34, так как мне нужны были барьеры. На ревью пока отдаю PR в COD-34, после того как Игорь сольёт свой код в dev, создам PR в dev.

2023-07-14 14:45 UTC, alexYurin approved these changes
Класс! Выглядит огонь!
Пару некритичных замечаний внес по поводу алиасов

2023-07-14 14:45 UTC, alexYurin commented on packages/client/src/engine/Core/index.ts
> +import BackgroundObject from '../Objects/Background'
Лучше использовать алиасы, а не относительные пути, если нужный файл лежит не в этой же директории
`../Objects/Background` -> `@/engine/Objects/Background`

2023-07-14 14:45 UTC, alexYurin commented on packages/client/src/engine/Objects/Background/index.ts
> +import BaseObject from '../Base'
Здесь и ниже, обрати, пожалуйста, внимание на алиасы)

2023-07-15 08:48 UTC, IvanPeleshok commented on packages/client/src/engine/Objects/Car/index.ts
> +      const car_position = getCarPosition()
Переменные именуем следующим образом:
https://learn.javascript.ru/variables#variable-naming
```
carPosition
```

2023-07-15 08:50 UTC, IvanPeleshok commented on packages/client/src/pages/Play/hooks/useEngine.ts
> +      Promise.all([loadImage(spriteImages), loadImage(backgroundImage)]).then(
Предлагаю воспользоваться async / await + try / catch
Так код будет иметь линейную структуру без колбеков
https://learn.javascript.ru/async-await

2023-07-15 08:51 UTC, IvanPeleshok requested changes
Есть замечания + поправить замечания, которые оставил тимейт

2023-07-16 13:18 UTC, IvanPeleshok commented on packages/client/src/engine/Objects/Barrier/index.ts
> +      const barrier_position = getPositionBarrier()
Переменные пытаемся писать в следующем стиле: barrierPosition

2023-07-16 13:19 UTC, IvanPeleshok approved these changes

2023-07-17 19:08 UTC, merged