COD 51
crazymaza/CodeBusters pull request #41
Opened 2023-07-30 12:08 UTC by crazymaza

### Какую задачу решаем
Добавление взаимодействия таблицы лидеров с api 

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-07-30 13:25 UTC, Avenntador commented on packages/client/src/pages/Play/hooks/useEngine.ts
> +  const user = useAppSelector(state => state.user.userInfo)
Селектор лучше использовать который у нас есть src\store\slices\userSlice\selectors.ts

2023-07-30 13:37 UTC, Avenntador commented on packages/client/src/pages/LeaderBoard/parts/customizedTable/index.tsx
> +  const leaderList = useAppSelector(state => state.leaderboard.data)
Здесь тоже селектор из leaderboardSlice/selectors

2023-07-30 13:47 UTC, Avenntador approved these changes
Хорошая работа, есть пара мелких замечаний, прежде чем мерджить, пусть еще кто нибудь проверит

2023-07-31 09:19 UTC, OlgaNoz reviewed
пару вопросиков

2023-07-31 09:19 UTC, OlgaNoz commented on packages/client/src/pages/LeaderBoard/functions.tsx
> +    case 1:
давайте вынесем эти цифры в отдельный enum

2023-07-31 09:19 UTC, OlgaNoz commented on packages/client/src/pages/LeaderBoard/parts/customizedTable/index.tsx
> +  const [orderBy, setOrderBy] = useState<keyof ILeaderList>('rating')
ниже были добавлены константы в data.ts нельзя их использовать?

2023-07-31 11:03 UTC, alexYurin reviewed
Небольшое замечание

2023-07-31 11:03 UTC, alexYurin commented on packages/client/src/pages/LeaderBoard/parts/tableHeader/data.ts
> +import { IHeaderCell } from '../../types'
Автоимпорты иногда предлагают не лучший вариант) Здесь и в других местах лучше через alias
`@/pages/LeaderBoard/types` чем относительный путь

2023-07-31 11:17 UTC, alexYurin commented on packages/client/src/pages/LeaderBoard/parts/customizedTable/index.tsx
> +import { Table, TableBody, TableRow, TableCell, Avatar } from '@mui/material'
Еще подумал, может сделаем, как например в остальных страницах (Game/Forum), где есть разбивка на компоненты
вместо папки `parts` -> `components `, и сами папки с названиями компонентов тоже с большой буквы `customizedTable` -> `CustomizedTable`

2023-08-02 08:11 UTC, alexYurin approved these changes

2023-08-02 08:19 UTC, OlgaNoz approved these changes
супер!

2023-08-02 21:41 UTC, IvanPeleshok commented on packages/client/src/pages/LeaderBoard/components/CustomizedTable/styles.module.scss
> +  }
Предлагаю добавлять в конце каждого файла оставлять пустую строку и вот почему: https://stackoverflow.com/questions/2287967/why-is-it-recommended-to-have-empty-line-in-the-end-of-a-source-file

2023-08-02 21:44 UTC, IvanPeleshok commented on packages/client/src/pages/LeaderBoard/components/CustomizedTable/index.tsx
> +    const isAsc = orderBy === property && order === OrderTypes.ASC
Я бы предложил в данном сценарии сразу вычитать направление сортировки
```
const direction = orderBy === property && order === OrderTypes.ASC
  ? OrderTypes.DESC
  :  OrderTypes.ASC
  
setOrder(direction)
...
```

2023-08-02 21:47 UTC, IvanPeleshok commented on packages/client/src/pages/LeaderBoard/components/TableHeader/index.tsx
> +            <TableSortLabel
```
<TableSortLabel
  active={orderBy === id}
  direction={orderBy === id ? order : 'asc'}
  onClick={createSortHandler(id)}
/>
```

2023-08-02 21:51 UTC, IvanPeleshok commented on packages/client/src/pages/LeaderBoard/components/TableHeader/styles.module.scss
> +}
Аналогично, стоит добавить пустую строку в конце файла

2023-08-02 21:56 UTC, IvanPeleshok commented on packages/client/src/store/slices/leaderboardSlice/thunks.ts
> +      return leaderboardData.data.reduce(
Предлагаю thunk оставлять чистыми без обработки ответа (вынести в slice)
Так поток данных будет более очевидным

2023-08-02 21:56 UTC, IvanPeleshok requested changes
Есть небольшие замечания

2023-08-03 18:07 UTC, crazymaza commented on packages/client/src/pages/LeaderBoard/components/TableHeader/index.tsx
> +            <TableSortLabel
> Такая запись была бы читабельнее
> 
> ```
> <TableSortLabel
>   active={orderBy === id}
>   direction={orderBy === id ? order : 'asc'}
>   onClick={createSortHandler(id)}
> />
> ```

Переделал чтобы подсвечивалась возможность сортировки при наведении на лейбл.

```js
<TableSortLabel
              active={orderBy === id}
              direction={orderBy === id ? order : 'asc'}
              onClick={createSortHandler(id)} 
            >
              {label}
            </TableSortLabel>
```

2023-08-03 22:08 UTC, IvanPeleshok approved these changes
Замечательная работа

2023-08-09 19:35 UTC, merged