remove alert
crazymaza/CodeBusters pull request #43
Opened 2023-08-03 16:50 UTC by OlgaNoz

### Какую задачу решаем
Убрала alert при проигрыше, теперь есть сообщение с результатом
Убрала страницу с окончанием игры за ненадобностью
Добавила кнопку с переходом на лидерборд со страницы с игрой

### Скриншоты/видяшка (если есть)

[refactor alert.webm](https://github.com/crazymaza/CodeBusters/assets/129430140/f8536d5a-9ce6-4e05-aac9-ca24bada7ab4)

### TBD (если есть)

2023-08-04 12:22 UTC, alexYurin reviewed
Круто! Но есть несколько небольших замечаний

2023-08-04 12:22 UTC, alexYurin commented on packages/client/src/engine/Core/index.ts
> +import EndGameMessageObject from '../Objects/EndGame'
Здесь и ниже, предлагаю придерживаться единого стиля импорта модулей через алиасы

2023-08-04 12:22 UTC, alexYurin commented on packages/client/src/engine/Objects/EndGame/index.ts
> +      )
Мб логические блоки разделить отступами, чтобы было читабельнее

2023-08-04 12:22 UTC, alexYurin commented on packages/client/src/pages/Play/components/GameControls/index.tsx
> +        }}>
Предлагаю вынести коллбэк в отдельную функцию

2023-08-04 14:34 UTC, OlgaNoz commented on packages/client/src/engine/Core/index.ts
> +import EndGameMessageObject from '../Objects/EndGame'
эх, вечно я про это забываю(

2023-08-04 15:39 UTC, alexYurin approved these changes
Отлично 👍

2023-08-05 10:01 UTC, crazymaza approved these changes

2023-08-05 14:21 UTC, Olegas requested changes
Добрый день.
Укажи пожалуйста, какую задачу из бэклога 7 спринта ты решаешь? Лучше всего указывать задачу бэклога в описании PR

2023-08-05 15:00 UTC, OlgaNoz commented
@Olegas из задач беклога, который у нас от яндекса составлен мне в этом спринте только memoryleaks досталась. А эта задача сложнее, но мы ее сами записывали

2023-08-06 07:47 UTC, merged