Cod 57
crazymaza/CodeBusters pull request #48
Opened 2023-08-11 16:37 UTC by crazymaza

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-08-11 16:50 UTC, OlgaNoz commented
Игорь, а расскажешь, как это запустить?)

2023-08-13 08:35 UTC, alexYurin commented
> Игорь, а расскажешь, как это запустить?)

Согласен, может куда-нибудь в README добавить

2023-08-15 18:35 UTC, alexYurin reviewed
Думаю, что не стоит удалять .env.sample а оставить его для примера, какие переменные окружения есть. А все явки и пароли у нас и так в .env, а он в .gitignore

2023-08-16 18:04 UTC, crazymaza commented
В корневом редми указаны команды для запуска. Там есть команда для генерации .env файла, поэтому вернул .env.sample обратно. 
Запускается это всё чудо командой docker-compose up. Нужно подождать пока скачаются все файлы и запустятся контейнеры.

2023-08-18 18:24 UTC, alexYurin approved these changes
Большая работа 💪

2023-08-19 11:56 UTC, Olegas requested changes
Есть одна маленькая неточность, давай исправим. Написал комментарий с подробностями.

2023-08-19 11:56 UTC, Olegas commented on docker-compose.yml
> +      - postgres
Этот сервис судя по конфигурации раздает статику. Зачем ему postgres? Скорее тут должна быть зависимость от server

2023-08-19 17:29 UTC, Olegas approved these changes
Работа принята, спасибо!

2023-08-23 18:34 UTC, merged