Cod 58
crazymaza/CodeBusters pull request #51
Opened 2023-08-16 20:43 UTC by OlgaNoz

### Какую задачу решаем

Реализовать API для форума:

Добавила 4 таблицы: 
- Users (id, displayName, firstName, secondName, avatar)
- Topics (id, title, description, userId)
- Comments (id, topicId, userId, text, parentCommentId)
- Reactions (id, commentId, userId, reaction)

API: 
Любой запрос содержит на http://localhost:3001/api/forum 
- Topics
    get('/topic/comments/:topicId') - получить список комментариев в виде дерева с реакциями и пользователями
    get('/topic') - получить список всех топиков
    get('/topic/top') - получить список 5 самых популярных топиков
    post('/topic') - добавить топик (body: {title, decription, userId})
    delete('/:topicId') - удалить топик
- Comment
    get('/comment/:commentId') - получить комментарий по id
    post('/comment') - добавить комментарий (body: {topicId, userId, text, parentCommentId?})
- Reactions 
    get('/reaction/:commentId') - получить реакции по id комментария
    post('/reaction') - добавить реакцию (body: {commentId, userId, reaction)
    delete('/reaction/:reactionId') - удалить реакцию
    
### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-08-17 06:41 UTC, crazymaza commented on packages/server/database/comment/controller/index.ts
> +  rootComments.forEach(comment => {
У тебя выше есть метод, который выдаёт нам родительский комментарий. Почему ты не используешь его, а передаёшь отдельный параметр?

2023-08-17 06:43 UTC, crazymaza commented on packages/server/database/comment/controller/index.ts
> +    const tree = getTopicCommentsTreeElements(comments, comment, treeRoot)
Можно сразу сделать return без присваивания.

2023-08-17 06:51 UTC, OlgaNoz commented on packages/server/database/comment/controller/index.ts
> +  rootComments.forEach(comment => {
резонно

2023-08-17 06:52 UTC, crazymaza commented on packages/server/database/comment/controller/index.ts
> +  } else {
Можно убрать блок else, так как у тебя в if уже идёт return. 

```js
if (!childComments.length) {
    return {
      comment: parentComment,
      replies: [],
    } as ITreeCommentElement
```

Либо в if вынести успешный кейс if(childComments.length){}, а уже после него без else возвращать где childComments.length будет равен нулю, т.е. просто 

```js
return {
      comment: parentComment,
      replies: [],
    } as ITreeCommentElement
```

2023-08-17 07:37 UTC, crazymaza commented on packages/server/database/comment/controller/index.ts
> +        res.status(200).json(treeComments)
А что потом происходит с этим res? Он куда-то дальше должен передаваться?

2023-08-17 07:44 UTC, crazymaza commented on packages/server/database/comment/model/index.ts
> +    field: 'topic_Id',
давай в названии полей Id напишем с маленькой буквы везде. Ну и вообще любое слово после _

2023-08-17 07:51 UTC, crazymaza commented on packages/server/database/comment/service/index.ts
> +  public async addComment(comment: IComment) {
может сделать деструктуризацию полей? 

```js 
 public async addComment({ text, topicId, userId, parentCommentId }: IComment) {
  text,
  topicId,
  comment.userId,
  parentCommentId // а вот тут я не знаю будет записываться null или нет
}
```

2023-08-17 07:52 UTC, OlgaNoz commented on packages/server/database/comment/controller/index.ts
> +        res.status(200).json(treeComments)
res.json отправляет ответ в виде json обратно на клиент

2023-08-17 07:53 UTC, crazymaza commented on packages/server/database/reaction/controller/index.ts
> +        res.status(200).json(reactions)
Такой же вопрос как и с комментарием. Не забыто ли здесь ключевое слово return?

2023-08-17 07:54 UTC, crazymaza commented on packages/server/database/comment/controller/index.ts
> +        res.json({ error: 'Failed to add new comment' })
Текст ошибки не соответствует методу.

2023-08-17 07:55 UTC, OlgaNoz commented on packages/server/database/reaction/controller/index.ts
> +        res.status(200).json(reactions)
не надо

2023-08-17 07:56 UTC, crazymaza commented on packages/server/database/reaction/controller/index.ts
> +        res.json({ error: 'Failed to get list of comment reactions reactions' })
2 раза повторяется reactions

2023-08-17 08:07 UTC, crazymaza commented on packages/server/database/reaction/service/index.ts
> +  public async addReaction(reaction: IReaction) {
можно деструктуризацией воспользоваться как для комментария

2023-08-17 08:15 UTC, crazymaza commented on packages/server/database/topic/controller/index.ts
> +      console.log(topics)
Думаю, что это лишнее.

2023-08-17 08:36 UTC, crazymaza commented on packages/server/database/topic/service/index.ts
> +    return Topic.findAll({
Мне не нравится, что ты в по сути делаешь ещё один запрос аналогичный getAllTopics() просто добавив сортировку по полю. Потом все данные тянешь в код и выбираешь первые 5. 
Почитал в интернете:
https://stackoverflow.com/questions/69662018/sequelize-how-return-rows-only-if-included-model-has-at-least-one-record
https://my-js.org/docs/guide/sequelize  здесь нужно искать строку "Настройки limit и offset позволяют ограничивать и/или пропускать определенное количество возвращаемых объектов:"

Ради академического опыта можно будет попробовать добавить лимит и оффсет к запросу, но это если будет желание, потому что могут быть проблемы из-за ```@HasMany```. 
Получится сделать - отлично! Нет - сойдёт текущее решение.

2023-08-17 08:38 UTC, crazymaza commented on packages/server/database/user/model/index.ts
> +    allowNull: false,
autoIncrement: true ?

2023-08-17 08:40 UTC, crazymaza reviewed
Есть замечания

2023-08-17 08:48 UTC, OlgaNoz commented on packages/server/database/user/model/index.ts
> +    allowNull: false,
не, здесь будет такой же id, как и у пользователя в яндексе

2023-08-17 08:48 UTC, OlgaNoz commented on packages/server/database/topic/service/index.ts
> +    return Topic.findAll({
я потому так и оставила, что не получилось(

2023-08-17 08:50 UTC, OlgaNoz commented on packages/server/database/topic/service/index.ts
> +    return Topic.findAll({
пробовала limit 5 делать, но ругался на связи вроде бы, уже не помню

2023-08-17 09:38 UTC, crazymaza approved these changes

2023-08-17 10:53 UTC, Avenntador approved these changes

2023-08-19 11:41 UTC, Olegas requested changes
Большая работа, супер!
Но есть проблемы. Написал о них в комментариях к коду.
Нужно доработать.

2023-08-19 11:41 UTC, Olegas commented on packages/client/vite.config.ts.timestamp-1692108119194.mjs
> +import { defineConfig } from "vite";
Это какой-то явно локальный файл. Тут вот даже локальный путь на машине разработчика. Думаю, его не надо комитить

2023-08-19 11:41 UTC, Olegas commented on lerna-debug.log
> +5 error     at ReaderSync.walkSync [as _walkSync] (/home/nozdrya/game/CodeBusters/node_modules/@nodelib/fs.walk/out/index.js:20:21)
Отладочные логи - думаю им не нужно быть в репозитории вообще. Надо убрать

2023-08-19 11:41 UTC, Olegas commented on packages/server/database/comment/controller/index.ts
> +  })
Если вы делаете новую коллекцию на основе существующей, для этого отлично подходит метод map - не надо делать новый результирующий массив, а сразу возвращаем результат map

2023-08-19 11:41 UTC, Olegas commented on packages/server/database/comment/model/index.ts
> +  declare topicId: number
По этому полю нужен индекс, т.к. вы ищете по этому полю комментарии. Foreign key не создает индекс сам по себе, это нужно сделать самостоятельно

2023-08-19 11:41 UTC, Olegas commented on packages/server/database/comment/service/index.ts
> +    return await Comment.create({
return await не имеет смысла (если только вы не ловите ошибки через try/catch). Здесь нет обработки ошибок, значит можно просто return Comment.create

2023-08-19 11:41 UTC, Olegas commented on packages/server/database/reaction/model/index.ts
> +  declare commentId: number
Так же нужен индекс т.к. по этому полю идет поиск

2023-08-19 11:41 UTC, Olegas commented on packages/server/database/reaction/service/index.ts
> +    return Reaction.create({
Уточните - у вас пользователь к одному комментарию может создавать сколько угодно реакций?

2023-08-19 11:41 UTC, Olegas commented on packages/server/database/reaction/controller/index.ts
> +        res.json({ error: 'Failed to add delete reaction' })
Что-то с текстом ошибки - add delete

2023-08-19 11:41 UTC, Olegas commented on packages/server/database/reaction/controller/index.ts
> +      res.status(400)
Немного странно что явно необработанное исключение превращается в ошибку 400 (bad request) а не 500 (internal server error). 500 обычно как раз для ситуаций когда все сломалось и непредсказуемо упало

2023-08-19 11:41 UTC, Olegas commented on packages/server/database/topic/service/index.ts
> +    })
Вообще вот такой запрос (этот, и выше findAll) - он очень тяжелый для базы
1. Нам надо достать все топики
2. Для каждого достать все комментарии (то есть по факту мы поднимем полностью две таблицы)
3. Затем посчитать кол-во комментариев
4. Отсортировать по ним, взять первые 5

То есть мы выкидываем большую часть работы.
Такие штуки начнут тормозить и греть базу если комментариев и топиков будет много.

Если уж очень надо делать топ по количеству, я бы сделал поле, в которое сохранял количество комментариев и поддерживал его в актуальном состоянии. Только это тоже не простая задача - нужно делать это аккуратно и правильно, что бы при конкурирующих запросах не наломать дров и не привести поле в некорректное состояние.

2023-08-19 11:41 UTC, Olegas commented on packages/server/middlewares/checkUser.ts
> +    }
Вот здесь есть проблема.
При конкурирующих запросах от одного пользователя вы можете прочитать БД, увидеть что пользователя нет и начать его создавать. В этом время другой запрос сделает то же самое. В итоге один из запросов не сможет создать пользователя, потому что нарушит уникальность первичного ключа.
Для этого в добавлении нужно использовать upsert

2023-08-19 17:32 UTC, OlgaNoz commented on packages/server/database/reaction/service/index.ts
> +    return Reaction.create({
да, может

2023-08-19 18:07 UTC, OlgaNoz commented on packages/server/database/topic/service/index.ts
> +    })
решили убрать запрос на получение топовых тем

2023-08-20 12:30 UTC, Olegas approved these changes
Отличная работа! Принято.

2023-08-21 09:17 UTC, merged