Cod 59
crazymaza/CodeBusters pull request #52
Opened 2023-08-18 12:24 UTC by alexYurin

### Подключение тем (Клиентская часть)

- Теперь темы сменяются
- При инициализации стора на сервере, если юзер залогинен, то идет запрос для получение темы пользователя

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-08-18 12:45 UTC, OlgaNoz reviewed
супер!

2023-08-18 12:45 UTC, OlgaNoz commented on packages/client/src/api/User/types.ts
> +export type ThemeType = 'dark' | 'light'
есть же ThemeNameEnum, мб его использовать?

2023-08-18 12:45 UTC, OlgaNoz commented on packages/client/entry.server.tsx
> +      console.log('theme is not set for user')
мб если тема для пользователя не задана, отправить запрос на то, чтобы ее задать?
ну или может и не надо, меня лично смущает, что это в try catch обернуто, ведь то, что у пользователя тема не задана по большому счету особой роли не играет

2023-08-18 14:48 UTC, alexYurin commented on packages/client/src/api/User/types.ts
> +export type ThemeType = 'dark' | 'light'
Поравил

2023-08-18 14:50 UTC, OlgaNoz approved these changes
молодец! все хорошо и быстро)

2023-08-18 17:21 UTC, Olegas requested changes
Добрый день.
Есть замечания/вопросы по коду.
Написал подробные комментарии.
Нужно либо прокомментировать, либо исправить

2023-08-18 17:21 UTC, Olegas commented on packages/client/src/api/User/types.ts
> +  userId: number
Кажется в 8 спринте у вас уже должна быть авторизация на ручках. Если это так, то идентификатор пользователя нужно брать из доверенного источника (из данных авторизации) а не из тела запроса. Иначе это может привести к тому, что я смогу поставить тему другому пользователю по его ID

2023-08-18 17:21 UTC, Olegas commented on packages/client/src/api/User/index.ts
> +  }
Совет (исправлять не требуется): вынести работу с темами в отдельное API. Это все же не работа с пользователем

2023-08-18 17:21 UTC, Olegas commented on packages/client/src/router/useAuth.ts
> +        await dispatch(getUserTheme(userInfo.id))
Еще один плюс от использования текущего авторизованного пользователя прямо на сервере - здесь не придется получать идентификатор пользователя

2023-08-19 13:00 UTC, alexYurin commented on packages/client/src/api/User/types.ts
> +  userId: number
Убрал userId из запроса темы на клиенте и добавил middleware на сервер для прокидывания id юзера

2023-08-19 13:02 UTC, alexYurin commented on packages/client/src/api/User/index.ts
> +  }
Вынес в отдельный сервис, тк теперь апи на клиенте к юзеру не привязано

2023-08-19 13:03 UTC, alexYurin commented on packages/client/src/router/useAuth.ts
> +        await dispatch(getUserTheme(userInfo.id))
Это поправил, т.к. необходимость передавать параметры в апи отпала

2023-08-19 13:26 UTC, Olegas commented on packages/server/middlewares/userThemeProvider.ts
> +    }
Так не очень правильно делать. Ты возможно перетираешь параметр чужой. Представь будет API например получения информации о пользователе и там будет параметр userId. Лучше такие вещи складывать в [locals](https://expressjs.com/en/api.html#res.locals)

2023-08-19 13:27 UTC, Olegas requested changes
Все супер, но в новой мидлваре есть проблема. Написал комментарий и как исправить.

2023-08-19 13:50 UTC, alexYurin commented on packages/server/middlewares/userThemeProvider.ts
> +    }
Спасибо, поправил и в GET и в POST запросах

2023-08-19 17:09 UTC, Olegas approved these changes
Отлично! Работа принята.

2023-08-21 10:51 UTC, merged